// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndxfqiwryuzjhwujqpca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5keGZxaXdyeXV6amh3dWpxcGNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MjAwNzIsImV4cCI6MjA3MjM5NjA3Mn0.KzIy8E7L1vClDmd01uT8vp2c9KUwOm3Ukam-x45HCEw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});